[technote]
id = "SQR-086"
series_id = "SQR"
canonical_url = "https://sqr-086.lsst.io"
github_url = "https://github.com/lsst-sqre/sqr-086"
github_default_branch = "main"
date_created = 2024-02-09T17:50:38Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"
note = "Architecture for the Ook link service and the Sphinx-domain based system for annotating documentation is well understood in this draft. The implemenation of a VO linking endpoint still needs design work."

[[technote.authors]]
internal_id = "sickj"
orcid = "https://orcid.org/0000-0003-3001-676X"
name = {given = "Jonathan", family = "Sick"}
[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "950 N. Cherry Ave., Tucson, AZ 85719, USA"
[[technote.authors.affiliations]]
name = "J.Sick Codes Inc."
internal_id = "JSickCodes"
address = "Penetanguishene, Ontario, Canada"
